const icon = type => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">${type === 'folder' ? '<path d="M3 7h7l2 2h9v11H3z"/><path d="M3 7V4h7l2 3"/>' : type === 'plus' ? '<path d="M12 5v14M5 12h14"/>' : type === 'settings' ? '<circle cx="12" cy="12" r="7"/><circle cx="12" cy="12" r="2"/>' : '<path d="M5 6h14M5 12h14M5 18h9"/>'}</svg>`;
function navigation(settings) {
 return `<aside class="app-shell-left-panel"><div class="sidebar-navigation"><nav role="navigation"><div class="traffic"><i></i><i></i><i></i></div><div class="brand">${icon('list')} Codex</div>${settings ? `<button class="sidebar-item" id="back">←　返回应用</button><div class="caption">个人</div><button class="sidebar-item" aria-current="page">${icon('settings')} 常规</button><button class="sidebar-item">${icon('list')} 通知</button><button class="sidebar-item">${icon('settings')} 外观</button><button class="sidebar-item">${icon('list')} 快捷键</button>` : `<button class="sidebar-item">${icon('plus')} 新对话</button><div class="caption">项目</div><button class="sidebar-item">${icon('folder')} Aurora Studio</button><button class="sidebar-item sub" aria-current="page">首页设计</button><button class="sidebar-item sub">整理交互细节</button><button class="sidebar-item">${icon('folder')} Orbit Notes</button><button class="sidebar-item sub">记录灵感</button><button class="sidebar-item">${icon('folder')} Demo Workspace</button><div class="caption">最近</div><button class="sidebar-item">一段轻松的编码时间</button><button class="sidebar-item">让工作空间动起来</button>`}<div class="bottom-nav"><button id="settings" class="sidebar-item">${icon('settings')} 设置</button><button class="sidebar-item"><span class="avatar">D</span> Demo User</button></div></nav></div></aside>`;
}
const heading = title => `<header class="topbar" data-app-shell-header-toolbar><div class="top-title" data-app-shell-page-header>${title}</div><div class="demo-badge">示例界面 · 实际壁纸渲染</div></header>`;
const chapter = (number,title,detail) => `<div class="chapter"><span class="chapter-number">${number}</span><span class="chapter-name">${title}</span><span class="chapter-desc">${detail}</span><span class="dots">${[1,2,3,4].map(n=>`<i class="${n===number?'active':''}"></i>`).join('')}</span></div>`;
window.showChat = function(number = 1) {
 document.getElementById('root').innerHTML = `<div class="layout">${navigation(false)}<main data-app-shell-main-surface="default">${heading('Aurora Studio / 首页设计')}<section class="content"><div class="eyebrow">A little motion. A calmer workspace.</div><h1 class="hero">CodeX 视频壁纸</h1><p class="subtitle">你的本地视频，成为整个工作空间的背景。</p><div class="messages"><div class="user-message" data-markdown-text-tone="user-message">帮我整理一个简洁的首页方案。</div><div class="assistant-message" data-markdown-text-style="assistant-message"><p class="assistant-title">先让重要的内容更容易被看到。</p><ul><li>保留清晰的标题和正文层级。</li><li>用轻盈的毛玻璃承托导航与内容。</li><li>让背景持续播放，切换页面也保持连贯。</li></ul><p class="text-secondary mini" style="margin-top:11px">示例对话与项目名称均为虚构。</p></div></div><div class="files-card max-w-[min(100%,var(--thread-resource-card-max-width,100%))]"><div class="file-header group/turn-diff-header"><span>已编辑 2 个文件</span><span class="green">+28 <span class="red">−4</span></span></div><div class="file-row group/turn-diff-file-row"><span>src/Home.tsx</span><span class="green">+18</span></div><div class="file-row group/turn-diff-file-row"><span>src/theme.css</span><span class="green">+10 <span class="red">−4</span></span></div></div></section><div class="composer" data-composer-surface-variant="default"><div class="ProseMirror" id="editor" contenteditable="true" role="textbox" aria-label="示例消息输入框" data-placeholder="随心输入">继续优化细节。</div><div class="composer-footer"><div class="composer-tools"><span style="font-size:20px">＋</span><span class="text-secondary">本地工作空间</span></div><div class="composer-tools"><span>Codex</span><span class="send">↑</span></div></div></div>${number===1 ? chapter(1,'完整视频背景','整块玻璃侧栏 · 保留背景原色') : number===2 ? chapter(2,'多视频轮播','自然播完后，600ms 柔和过渡') : chapter(4,'回到对话','同一个视频图层 · 持续播放')}</main></div>`;
 document.getElementById('settings').onclick = window.showSettings;
};
window.showSettings = function() {
 document.getElementById('root').innerHTML = `<div class="layout">${navigation(true)}<main data-app-shell-main-surface="default">${heading('设置 / 常规')}<section class="group/settings group-settings"><h1 class="settings-title">常规</h1><p class="setting-section text-secondary">工作空间</p><div class="settings-group rounded-2xl" style="background-color:var(--color-background-panel)"><div class="setting-row"><div><p class="setting-label">语言</p><p class="setting-help">用于界面显示的语言</p></div><button class="value">简体中文 ﹀</button></div><div class="setting-row"><div><p class="setting-label">默认文件打开位置</p><p class="setting-help">打开工作空间中的文件</p></div><button class="value">Finder ﹀</button></div><div class="setting-row"><div><p class="setting-label">运行时防止系统睡眠</p><p class="setting-help">任务进行时保持电脑唤醒</p></div><button class="switch" aria-label="运行时防止系统睡眠" role="switch" aria-checked="true"></button></div></div><p class="setting-section text-secondary">界面</p><div class="settings-group rounded-2xl" style="background-color:var(--color-background-panel)"><div class="setting-row"><div><p class="setting-label">提示词建议</p><p class="setting-help">显示相关建议与下一步操作</p></div><button class="switch" aria-label="提示词建议" role="switch" aria-checked="true"></button></div><div class="setting-row"><div><p class="setting-label">默认终端位置</p><p class="setting-help">选择终端面板的打开位置</p></div><button class="value">底部 ﹀</button></div></div><p class="settings-note text-secondary">正文、辅助文字和控件分别保持自己的层级。<br>切换到设置页，视频依旧在同一图层播放。</p></section>${chapter(3,'设置页面适配','局部毛玻璃 · 清晰的文字层级')}</main></div>`;
 document.getElementById('back').onclick=()=>window.showChat(4);
};
window.showChat();
